import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';
import { supabase } from '@/integrations/supabase/client';
import { useApp } from '@/contexts/AppContext';

export type LanguageCode = 'en' | 'hi' | 'ta' | 'te' | 'kn' | 'bn' | 'mr' | 'gu' | 'pa' | 'ml';

export const LANGUAGES: { code: LanguageCode; label: string; nativeLabel: string }[] = [
  { code: 'en', label: 'English', nativeLabel: 'English' },
  { code: 'hi', label: 'Hindi', nativeLabel: 'हिन्दी' },
  { code: 'ta', label: 'Tamil', nativeLabel: 'தமிழ்' },
  { code: 'te', label: 'Telugu', nativeLabel: 'తెలుగు' },
  { code: 'kn', label: 'Kannada', nativeLabel: 'ಕನ್ನಡ' },
  { code: 'bn', label: 'Bengali', nativeLabel: 'বাংলা' },
  { code: 'mr', label: 'Marathi', nativeLabel: 'मराठी' },
  { code: 'gu', label: 'Gujarati', nativeLabel: 'ગુજરાતી' },
  { code: 'pa', label: 'Punjabi', nativeLabel: 'ਪੰਜਾਬੀ' },
  { code: 'ml', label: 'Malayalam', nativeLabel: 'മലയാളം' },
];

type TranslationKeys = {
  // Common
  welcome: string;
  goodMorning: string;
  hello: string;
  logout: string;
  back: string;
  cancel: string;
  save: string;
  delete: string;
  edit: string;
  add: string;
  search: string;
  loading: string;
  noResults: string;

  // Auth
  createAccount: string;
  signIn: string;
  signUp: string;
  email: string;
  password: string;
  fullName: string;
  phone: string;
  farmName: string;
  selectLanguage: string;
  alreadyHaveAccount: string;
  fillDetails: string;
  signingUpAs: string;
  creatingAccount: string;

  // Navigation
  dashboard: string;
  products: string;
  orders: string;
  climate: string;
  pricing: string;
  chat: string;
  qualityScan: string;
  home: string;
  browse: string;
  cart: string;
  overview: string;
  users: string;
  revenue: string;
  disputes: string;
  settings: string;

  // Farmer
  myProducts: string;
  addProduct: string;
  productsListed: string;
  noProductsYet: string;
  addFirstProduct: string;
  productName: string;
  price: string;
  category: string;
  unit: string;
  grade: string;
  description: string;
  organicProduct: string;
  inStock: string;
  outOfStock: string;
  todaysEarnings: string;
  activeOrders: string;
  aiPriceScore: string;
  weeklyEarnings: string;
  recentOrders: string;
  viewAll: string;
  aiInsights: string;
  farmOverview: string;

  // Consumer
  freshProduce: string;
  freshFromFarm: string;
  searchProducts: string;
  nearbyFarms: string;
  addToCart: string;
  discoverFarms: string;
  all: string;
  vegetables: string;
  fruits: string;
  grains: string;
  dairy: string;
  organic: string;

  // Portal labels
  farmerPortal: string;
  consumerPortal: string;
  adminPortal: string;
};

const translations: Record<LanguageCode, TranslationKeys> = {
  en: {
    welcome: 'Welcome',
    goodMorning: 'Good Morning',
    hello: 'Hello',
    logout: 'Logout',
    back: 'Back',
    cancel: 'Cancel',
    save: 'Save',
    delete: 'Delete',
    edit: 'Edit',
    add: 'Add',
    search: 'Search',
    loading: 'Loading...',
    noResults: 'No results found',
    createAccount: 'Create Account',
    signIn: 'Sign in',
    signUp: 'Sign Up',
    email: 'Email',
    password: 'Password',
    fullName: 'Full Name',
    phone: 'Phone',
    farmName: 'Farm Name / Location',
    selectLanguage: 'Preferred Language',
    alreadyHaveAccount: 'Already have an account?',
    fillDetails: 'Fill in your details to get started',
    signingUpAs: 'Signing up as',
    creatingAccount: 'Creating...',
    dashboard: 'Dashboard',
    products: 'Products',
    orders: 'Orders',
    climate: 'Climate',
    pricing: 'Pricing',
    chat: 'Chat',
    qualityScan: 'Quality Scan',
    home: 'Home',
    browse: 'Browse',
    cart: 'Cart',
    overview: 'Overview',
    users: 'Users',
    revenue: 'Revenue',
    disputes: 'Disputes',
    settings: 'Settings',
    myProducts: 'My Products',
    addProduct: 'Add Product',
    productsListed: 'products listed',
    noProductsYet: 'No products yet',
    addFirstProduct: 'Add your first product to start selling to consumers.',
    productName: 'Product Name',
    price: 'Price',
    category: 'Category',
    unit: 'Unit',
    grade: 'Grade',
    description: 'Description',
    organicProduct: 'Organic Product',
    inStock: 'In Stock',
    outOfStock: 'Out of Stock',
    todaysEarnings: "Today's Earnings",
    activeOrders: 'Active Orders',
    aiPriceScore: 'AI Price Score',
    weeklyEarnings: 'Weekly Earnings',
    recentOrders: 'Recent Orders',
    viewAll: 'View All',
    aiInsights: '🤖 AI Insights',
    farmOverview: "Here's your farm overview for today",
    freshProduce: 'Fresh Produce',
    freshFromFarm: 'Fresh from farm to your table',
    searchProducts: 'Search products, farms...',
    nearbyFarms: 'Nearby Farms',
    addToCart: 'Add to Cart',
    discoverFarms: 'Discover Farms',
    all: 'All',
    vegetables: 'Vegetables',
    fruits: 'Fruits',
    grains: 'Grains',
    dairy: 'Dairy',
    organic: 'Organic',
    farmerPortal: 'Farmer Portal',
    consumerPortal: 'Consumer Portal',
    adminPortal: 'Admin Portal',
  },
  hi: {
    welcome: 'स्वागत है',
    goodMorning: 'सुप्रभात',
    hello: 'नमस्ते',
    logout: 'लॉग आउट',
    back: 'वापस',
    cancel: 'रद्द करें',
    save: 'सहेजें',
    delete: 'हटाएं',
    edit: 'संपादित करें',
    add: 'जोड़ें',
    search: 'खोजें',
    loading: 'लोड हो रहा है...',
    noResults: 'कोई परिणाम नहीं मिला',
    createAccount: 'खाता बनाएं',
    signIn: 'साइन इन करें',
    signUp: 'साइन अप करें',
    email: 'ईमेल',
    password: 'पासवर्ड',
    fullName: 'पूरा नाम',
    phone: 'फ़ोन',
    farmName: 'खेत का नाम / स्थान',
    selectLanguage: 'पसंदीदा भाषा',
    alreadyHaveAccount: 'पहले से खाता है?',
    fillDetails: 'शुरू करने के लिए अपनी जानकारी भरें',
    signingUpAs: 'के रूप में साइन अप कर रहे हैं',
    creatingAccount: 'बनाया जा रहा है...',
    dashboard: 'डैशबोर्ड',
    products: 'उत्पाद',
    orders: 'ऑर्डर',
    climate: 'मौसम',
    pricing: 'मूल्य निर्धारण',
    chat: 'चैट',
    qualityScan: 'गुणवत्ता स्कैन',
    home: 'होम',
    browse: 'ब्राउज़',
    cart: 'कार्ट',
    overview: 'अवलोकन',
    users: 'उपयोगकर्ता',
    revenue: 'राजस्व',
    disputes: 'विवाद',
    settings: 'सेटिंग्स',
    myProducts: 'मेरे उत्पाद',
    addProduct: 'उत्पाद जोड़ें',
    productsListed: 'उत्पाद सूचीबद्ध',
    noProductsYet: 'अभी तक कोई उत्पाद नहीं',
    addFirstProduct: 'उपभोक्ताओं को बेचने के लिए अपना पहला उत्पाद जोड़ें।',
    productName: 'उत्पाद का नाम',
    price: 'कीमत',
    category: 'श्रेणी',
    unit: 'इकाई',
    grade: 'ग्रेड',
    description: 'विवरण',
    organicProduct: 'जैविक उत्पाद',
    inStock: 'स्टॉक में',
    outOfStock: 'स्टॉक में नहीं',
    todaysEarnings: 'आज की कमाई',
    activeOrders: 'सक्रिय ऑर्डर',
    aiPriceScore: 'AI मूल्य स्कोर',
    weeklyEarnings: 'साप्ताहिक कमाई',
    recentOrders: 'हाल के ऑर्डर',
    viewAll: 'सभी देखें',
    aiInsights: '🤖 AI अंतर्दृष्टि',
    farmOverview: 'आज का आपका खेत का अवलोकन',
    freshProduce: 'ताज़ा उपज',
    freshFromFarm: 'खेत से सीधे आपकी मेज़ तक',
    searchProducts: 'उत्पाद, खेत खोजें...',
    nearbyFarms: 'आस-पास के खेत',
    addToCart: 'कार्ट में जोड़ें',
    discoverFarms: 'खेत खोजें',
    all: 'सभी',
    vegetables: 'सब्ज़ियां',
    fruits: 'फल',
    grains: 'अनाज',
    dairy: 'डेयरी',
    organic: 'जैविक',
    farmerPortal: 'किसान पोर्टल',
    consumerPortal: 'उपभोक्ता पोर्टल',
    adminPortal: 'एडमिन पोर्टल',
  },
  ta: {
    welcome: 'வரவேற்கிறோம்',
    goodMorning: 'காலை வணக்கம்',
    hello: 'வணக்கம்',
    logout: 'வெளியேறு',
    back: 'பின்செல்',
    cancel: 'ரத்து',
    save: 'சேமி',
    delete: 'நீக்கு',
    edit: 'திருத்து',
    add: 'சேர்',
    search: 'தேடு',
    loading: 'ஏற்றுகிறது...',
    noResults: 'முடிவுகள் இல்லை',
    createAccount: 'கணக்கை உருவாக்கு',
    signIn: 'உள்நுழை',
    signUp: 'பதிவு செய்',
    email: 'மின்னஞ்சல்',
    password: 'கடவுச்சொல்',
    fullName: 'முழு பெயர்',
    phone: 'தொலைபேசி',
    farmName: 'பண்ணை பெயர் / இடம்',
    selectLanguage: 'விருப்ப மொழி',
    alreadyHaveAccount: 'ஏற்கனவே கணக்கு உள்ளதா?',
    fillDetails: 'தொடங்க விவரங்களை நிரப்பவும்',
    signingUpAs: 'ஆக பதிவு செய்கிறீர்கள்',
    creatingAccount: 'உருவாக்குகிறது...',
    dashboard: 'டாஷ்போர்ட்',
    products: 'பொருட்கள்',
    orders: 'ஆர்டர்கள்',
    climate: 'காலநிலை',
    pricing: 'விலை நிர்ணயம்',
    chat: 'அரட்டை',
    qualityScan: 'தர ஸ்கேன்',
    home: 'முகப்பு',
    browse: 'உலாவு',
    cart: 'கூடை',
    overview: 'மேலோட்டம்',
    users: 'பயனர்கள்',
    revenue: 'வருவாய்',
    disputes: 'தகராறுகள்',
    settings: 'அமைப்புகள்',
    myProducts: 'என் பொருட்கள்',
    addProduct: 'பொருள் சேர்',
    productsListed: 'பொருட்கள் பட்டியலிடப்பட்டுள்ளன',
    noProductsYet: 'இன்னும் பொருட்கள் இல்லை',
    addFirstProduct: 'நுகர்வோருக்கு விற்க முதல் பொருளை சேர்க்கவும்.',
    productName: 'பொருள் பெயர்',
    price: 'விலை',
    category: 'வகை',
    unit: 'அலகு',
    grade: 'தரம்',
    description: 'விளக்கம்',
    organicProduct: 'இயற்கை பொருள்',
    inStock: 'இருப்பில் உள்ளது',
    outOfStock: 'இருப்பில் இல்லை',
    todaysEarnings: 'இன்றைய வருமானம்',
    activeOrders: 'செயலில் ஆர்டர்கள்',
    aiPriceScore: 'AI விலை மதிப்பெண்',
    weeklyEarnings: 'வாரந்திர வருமானம்',
    recentOrders: 'சமீபத்திய ஆர்டர்கள்',
    viewAll: 'அனைத்தும் காண',
    aiInsights: '🤖 AI நுண்ணறிவு',
    farmOverview: 'இன்றைய பண்ணை மேலோட்டம்',
    freshProduce: 'புதிய விளைபொருள்',
    freshFromFarm: 'பண்ணையிலிருந்து நேரடியாக',
    searchProducts: 'பொருட்கள், பண்ணைகள் தேடு...',
    nearbyFarms: 'அருகிலுள்ள பண்ணைகள்',
    addToCart: 'கூடையில் சேர்',
    discoverFarms: 'பண்ணைகளை கண்டறி',
    all: 'அனைத்தும்',
    vegetables: 'காய்கறிகள்',
    fruits: 'பழங்கள்',
    grains: 'தானியங்கள்',
    dairy: 'பால் பொருட்கள்',
    organic: 'இயற்கை',
    farmerPortal: 'விவசாயி போர்டல்',
    consumerPortal: 'நுகர்வோர் போர்டல்',
    adminPortal: 'நிர்வாக போர்டல்',
  },
  te: {
    welcome: 'స్వాగతం',
    goodMorning: 'శుభోదయం',
    hello: 'హలో',
    logout: 'లాగ్ అవుట్',
    back: 'వెనుకకు',
    cancel: 'రద్దు',
    save: 'సేవ్',
    delete: 'తొలగించు',
    edit: 'సవరించు',
    add: 'జోడించు',
    search: 'వెతుకు',
    loading: 'లోడ్ అవుతోంది...',
    noResults: 'ఫలితాలు లేవు',
    createAccount: 'ఖాతా సృష్టించు',
    signIn: 'సైన్ ఇన్',
    signUp: 'సైన్ అప్',
    email: 'ఇమెయిల్',
    password: 'పాస్‌వర్డ్',
    fullName: 'పూర్తి పేరు',
    phone: 'ఫోన్',
    farmName: 'పొలం పేరు / స్థానం',
    selectLanguage: 'ఇష్టమైన భాష',
    alreadyHaveAccount: 'ఇప్పటికే ఖాతా ఉందా?',
    fillDetails: 'ప్రారంభించడానికి వివరాలు నమోదు చేయండి',
    signingUpAs: 'గా సైన్ అప్ చేస్తున్నారు',
    creatingAccount: 'సృష్టిస్తోంది...',
    dashboard: 'డాష్‌బోర్డ్',
    products: 'ఉత్పత్తులు',
    orders: 'ఆర్డర్లు',
    climate: 'వాతావరణం',
    pricing: 'ధరలు',
    chat: 'చాట్',
    qualityScan: 'నాణ్యత స్కాన్',
    home: 'హోమ్',
    browse: 'బ్రౌజ్',
    cart: 'కార్ట్',
    overview: 'అవలోకనం',
    users: 'వినియోగదారులు',
    revenue: 'ఆదాయం',
    disputes: 'వివాదాలు',
    settings: 'సెట్టింగ్‌లు',
    myProducts: 'నా ఉత్పత్తులు',
    addProduct: 'ఉత్పత్తి జోడించు',
    productsListed: 'ఉత్పత్తులు జాబితా చేయబడ్డాయి',
    noProductsYet: 'ఇంకా ఉత్పత్తులు లేవు',
    addFirstProduct: 'వినియోగదారులకు విక్రయించడానికి మీ మొదటి ఉత్పత్తిని జోడించండి.',
    productName: 'ఉత్పత్తి పేరు',
    price: 'ధర',
    category: 'వర్గం',
    unit: 'యూనిట్',
    grade: 'గ్రేడ్',
    description: 'వివరణ',
    organicProduct: 'సేంద్రీయ ఉత్పత్తి',
    inStock: 'స్టాక్‌లో ఉంది',
    outOfStock: 'స్టాక్‌లో లేదు',
    todaysEarnings: 'నేటి ఆదాయం',
    activeOrders: 'యాక్టివ్ ఆర్డర్లు',
    aiPriceScore: 'AI ధర స్కోర్',
    weeklyEarnings: 'వారపు ఆదాయం',
    recentOrders: 'ఇటీవలి ఆర్డర్లు',
    viewAll: 'అన్నీ చూడండి',
    aiInsights: '🤖 AI అంతర్దృష్టులు',
    farmOverview: 'నేటి మీ పొలం అవలోకనం',
    freshProduce: 'తాజా ఉత్పత్తులు',
    freshFromFarm: 'పొలం నుండి నేరుగా మీ బల్లకు',
    searchProducts: 'ఉత్పత్తులు, పొలాలు వెతకండి...',
    nearbyFarms: 'సమీపంలోని పొలాలు',
    addToCart: 'కార్ట్‌కు జోడించు',
    discoverFarms: 'పొలాలు కనుగొనండి',
    all: 'అన్ని',
    vegetables: 'కూరగాయలు',
    fruits: 'పండ్లు',
    grains: 'ధాన్యాలు',
    dairy: 'పాల ఉత్పత్తులు',
    organic: 'సేంద్రీయ',
    farmerPortal: 'రైతు పోర్టల్',
    consumerPortal: 'వినియోగదారు పోర్టల్',
    adminPortal: 'అడ్మిన్ పోర్టల్',
  },
  kn: {
    welcome: 'ಸ್ವಾಗತ',
    goodMorning: 'ಶುಭೋದಯ',
    hello: 'ನಮಸ್ಕಾರ',
    logout: 'ಲಾಗ್ ಔಟ್',
    back: 'ಹಿಂದೆ',
    cancel: 'ರದ್ದು',
    save: 'ಉಳಿಸಿ',
    delete: 'ಅಳಿಸಿ',
    edit: 'ಸಂಪಾದಿಸಿ',
    add: 'ಸೇರಿಸಿ',
    search: 'ಹುಡುಕಿ',
    loading: 'ಲೋಡ್ ಆಗುತ್ತಿದೆ...',
    noResults: 'ಫಲಿತಾಂಶಗಳಿಲ್ಲ',
    createAccount: 'ಖಾತೆ ರಚಿಸಿ',
    signIn: 'ಸೈನ್ ಇನ್',
    signUp: 'ಸೈನ್ ಅಪ್',
    email: 'ಇಮೇಲ್',
    password: 'ಪಾಸ್‌ವರ್ಡ್',
    fullName: 'ಪೂರ್ಣ ಹೆಸರು',
    phone: 'ಫೋನ್',
    farmName: 'ಕೃಷಿ ಹೆಸರು / ಸ್ಥಳ',
    selectLanguage: 'ಆದ್ಯತೆಯ ಭಾಷೆ',
    alreadyHaveAccount: 'ಈಗಾಗಲೇ ಖಾತೆ ಇದೆಯೇ?',
    fillDetails: 'ಪ್ರಾರಂಭಿಸಲು ವಿವರಗಳನ್ನು ತುಂಬಿ',
    signingUpAs: 'ಆಗಿ ಸೈನ್ ಅಪ್ ಆಗುತ್ತಿದ್ದೀರಿ',
    creatingAccount: 'ರಚಿಸಲಾಗುತ್ತಿದೆ...',
    dashboard: 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
    products: 'ಉತ್ಪನ್ನಗಳು',
    orders: 'ಆರ್ಡರ್‌ಗಳು',
    climate: 'ಹವಾಮಾನ',
    pricing: 'ಬೆಲೆ',
    chat: 'ಚಾಟ್',
    qualityScan: 'ಗುಣಮಟ್ಟ ಸ್ಕ್ಯಾನ್',
    home: 'ಮುಖಪುಟ',
    browse: 'ಬ್ರೌಸ್',
    cart: 'ಕಾರ್ಟ್',
    overview: 'ಅವಲೋಕನ',
    users: 'ಬಳಕೆದಾರರು',
    revenue: 'ಆದಾಯ',
    disputes: 'ವಿವಾದಗಳು',
    settings: 'ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
    myProducts: 'ನನ್ನ ಉತ್ಪನ್ನಗಳು',
    addProduct: 'ಉತ್ಪನ್ನ ಸೇರಿಸಿ',
    productsListed: 'ಉತ್ಪನ್ನಗಳು ಪಟ್ಟಿ ಮಾಡಲಾಗಿದೆ',
    noProductsYet: 'ಇನ್ನೂ ಉತ್ಪನ್ನಗಳಿಲ್ಲ',
    addFirstProduct: 'ಗ್ರಾಹಕರಿಗೆ ಮಾರಾಟ ಮಾಡಲು ನಿಮ್ಮ ಮೊದಲ ಉತ್ಪನ್ನವನ್ನು ಸೇರಿಸಿ.',
    productName: 'ಉತ್ಪನ್ನ ಹೆಸರು',
    price: 'ಬೆಲೆ',
    category: 'ವರ್ಗ',
    unit: 'ಘಟಕ',
    grade: 'ಗ್ರೇಡ್',
    description: 'ವಿವರಣೆ',
    organicProduct: 'ಸಾವಯವ ಉತ್ಪನ್ನ',
    inStock: 'ಸ್ಟಾಕ್‌ನಲ್ಲಿದೆ',
    outOfStock: 'ಸ್ಟಾಕ್‌ನಲ್ಲಿಲ್ಲ',
    todaysEarnings: 'ಇಂದಿನ ಆದಾಯ',
    activeOrders: 'ಸಕ್ರಿಯ ಆರ್ಡರ್‌ಗಳು',
    aiPriceScore: 'AI ಬೆಲೆ ಸ್ಕೋರ್',
    weeklyEarnings: 'ವಾರದ ಆದಾಯ',
    recentOrders: 'ಇತ್ತೀಚಿನ ಆರ್ಡರ್‌ಗಳು',
    viewAll: 'ಎಲ್ಲಾ ನೋಡಿ',
    aiInsights: '🤖 AI ಒಳನೋಟಗಳು',
    farmOverview: 'ಇಂದಿನ ನಿಮ್ಮ ಕೃಷಿ ಅವಲೋಕನ',
    freshProduce: 'ತಾಜಾ ಉತ್ಪನ್ನ',
    freshFromFarm: 'ಕೃಷಿಯಿಂದ ನೇರವಾಗಿ',
    searchProducts: 'ಉತ್ಪನ್ನಗಳು, ಕೃಷಿ ಹುಡುಕಿ...',
    nearbyFarms: 'ಸಮೀಪದ ಕೃಷಿಗಳು',
    addToCart: 'ಕಾರ್ಟ್‌ಗೆ ಸೇರಿಸಿ',
    discoverFarms: 'ಕೃಷಿಗಳನ್ನು ಕಂಡುಹಿಡಿಯಿರಿ',
    all: 'ಎಲ್ಲಾ',
    vegetables: 'ತರಕಾರಿಗಳು',
    fruits: 'ಹಣ್ಣುಗಳು',
    grains: 'ಧಾನ್ಯಗಳು',
    dairy: 'ಹಾಲು ಉತ್ಪನ್ನಗಳು',
    organic: 'ಸಾವಯವ',
    farmerPortal: 'ರೈತ ಪೋರ್ಟಲ್',
    consumerPortal: 'ಗ್ರಾಹಕ ಪೋರ್ಟಲ್',
    adminPortal: 'ಅಡ್ಮಿನ್ ಪೋರ್ಟಲ್',
  },
  bn: {
    welcome: 'স্বাগতম',
    goodMorning: 'সুপ্রভাত',
    hello: 'হ্যালো',
    logout: 'লগ আউট',
    back: 'পিছনে',
    cancel: 'বাতিল',
    save: 'সংরক্ষণ',
    delete: 'মুছুন',
    edit: 'সম্পাদনা',
    add: 'যোগ করুন',
    search: 'অনুসন্ধান',
    loading: 'লোড হচ্ছে...',
    noResults: 'কোনো ফলাফল নেই',
    createAccount: 'অ্যাকাউন্ট তৈরি করুন',
    signIn: 'সাইন ইন',
    signUp: 'সাইন আপ',
    email: 'ইমেইল',
    password: 'পাসওয়ার্ড',
    fullName: 'পুরো নাম',
    phone: 'ফোন',
    farmName: 'খামারের নাম / অবস্থান',
    selectLanguage: 'পছন্দের ভাষা',
    alreadyHaveAccount: 'ইতিমধ্যে অ্যাকাউন্ট আছে?',
    fillDetails: 'শুরু করতে তথ্য পূরণ করুন',
    signingUpAs: 'হিসেবে সাইন আপ করছেন',
    creatingAccount: 'তৈরি হচ্ছে...',
    dashboard: 'ড্যাশবোর্ড',
    products: 'পণ্য',
    orders: 'অর্ডার',
    climate: 'জলবায়ু',
    pricing: 'মূল্য নির্ধারণ',
    chat: 'চ্যাট',
    qualityScan: 'গুণমান স্ক্যান',
    home: 'হোম',
    browse: 'ব্রাউজ',
    cart: 'কার্ট',
    overview: 'সারসংক্ষেপ',
    users: 'ব্যবহারকারী',
    revenue: 'রাজস্ব',
    disputes: 'বিরোধ',
    settings: 'সেটিংস',
    myProducts: 'আমার পণ্য',
    addProduct: 'পণ্য যোগ করুন',
    productsListed: 'পণ্য তালিকাভুক্ত',
    noProductsYet: 'এখনো কোনো পণ্য নেই',
    addFirstProduct: 'গ্রাহকদের কাছে বিক্রি শুরু করতে প্রথম পণ্য যোগ করুন।',
    productName: 'পণ্যের নাম',
    price: 'দাম',
    category: 'বিভাগ',
    unit: 'একক',
    grade: 'গ্রেড',
    description: 'বিবরণ',
    organicProduct: 'জৈব পণ্য',
    inStock: 'মজুত আছে',
    outOfStock: 'মজুত নেই',
    todaysEarnings: 'আজকের আয়',
    activeOrders: 'সক্রিয় অর্ডার',
    aiPriceScore: 'AI মূল্য স্কোর',
    weeklyEarnings: 'সাপ্তাহিক আয়',
    recentOrders: 'সাম্প্রতিক অর্ডার',
    viewAll: 'সব দেখুন',
    aiInsights: '🤖 AI অন্তর্দৃষ্টি',
    farmOverview: 'আজকের আপনার খামারের সারসংক্ষেপ',
    freshProduce: 'তাজা পণ্য',
    freshFromFarm: 'খামার থেকে সরাসরি আপনার টেবিলে',
    searchProducts: 'পণ্য, খামার খুঁজুন...',
    nearbyFarms: 'কাছের খামার',
    addToCart: 'কার্টে যোগ করুন',
    discoverFarms: 'খামার আবিষ্কার করুন',
    all: 'সব',
    vegetables: 'শাকসবজি',
    fruits: 'ফল',
    grains: 'শস্য',
    dairy: 'দুগ্ধ',
    organic: 'জৈব',
    farmerPortal: 'কৃষক পোর্টাল',
    consumerPortal: 'গ্রাহক পোর্টাল',
    adminPortal: 'অ্যাডমিন পোর্টাল',
  },
  mr: {
    welcome: 'स्वागत',
    goodMorning: 'सुप्रभात',
    hello: 'नमस्कार',
    logout: 'बाहेर पडा',
    back: 'मागे',
    cancel: 'रद्द करा',
    save: 'जतन करा',
    delete: 'हटवा',
    edit: 'संपादित करा',
    add: 'जोडा',
    search: 'शोधा',
    loading: 'लोड होत आहे...',
    noResults: 'कोणतेही निकाल नाहीत',
    createAccount: 'खाते तयार करा',
    signIn: 'साइन इन',
    signUp: 'साइन अप',
    email: 'ईमेल',
    password: 'पासवर्ड',
    fullName: 'पूर्ण नाव',
    phone: 'फोन',
    farmName: 'शेताचे नाव / स्थान',
    selectLanguage: 'पसंतीची भाषा',
    alreadyHaveAccount: 'आधीच खाते आहे?',
    fillDetails: 'सुरू करण्यासाठी तपशील भरा',
    signingUpAs: 'म्हणून साइन अप करत आहात',
    creatingAccount: 'तयार होत आहे...',
    dashboard: 'डॅशबोर्ड',
    products: 'उत्पादने',
    orders: 'ऑर्डर',
    climate: 'हवामान',
    pricing: 'किंमत',
    chat: 'चॅट',
    qualityScan: 'गुणवत्ता स्कॅन',
    home: 'मुख्यपृष्ठ',
    browse: 'ब्राउझ',
    cart: 'कार्ट',
    overview: 'आढावा',
    users: 'वापरकर्ते',
    revenue: 'महसूल',
    disputes: 'वाद',
    settings: 'सेटिंग्ज',
    myProducts: 'माझी उत्पादने',
    addProduct: 'उत्पादन जोडा',
    productsListed: 'उत्पादने सूचीबद्ध',
    noProductsYet: 'अजून उत्पादने नाहीत',
    addFirstProduct: 'ग्राहकांना विक्री करण्यासाठी पहिले उत्पादन जोडा.',
    productName: 'उत्पादनाचे नाव',
    price: 'किंमत',
    category: 'श्रेणी',
    unit: 'एकक',
    grade: 'दर्जा',
    description: 'वर्णन',
    organicProduct: 'सेंद्रिय उत्पादन',
    inStock: 'स्टॉकमध्ये',
    outOfStock: 'स्टॉकमध्ये नाही',
    todaysEarnings: 'आजचे उत्पन्न',
    activeOrders: 'सक्रिय ऑर्डर',
    aiPriceScore: 'AI किंमत स्कोअर',
    weeklyEarnings: 'साप्ताहिक उत्पन्न',
    recentOrders: 'अलीकडील ऑर्डर',
    viewAll: 'सर्व पहा',
    aiInsights: '🤖 AI अंतर्दृष्टी',
    farmOverview: 'आजचा तुमच्या शेताचा आढावा',
    freshProduce: 'ताजी उत्पादने',
    freshFromFarm: 'शेतातून थेट तुमच्या टेबलावर',
    searchProducts: 'उत्पादने, शेते शोधा...',
    nearbyFarms: 'जवळची शेते',
    addToCart: 'कार्टमध्ये जोडा',
    discoverFarms: 'शेते शोधा',
    all: 'सर्व',
    vegetables: 'भाज्या',
    fruits: 'फळे',
    grains: 'धान्य',
    dairy: 'दुग्ध',
    organic: 'सेंद्रिय',
    farmerPortal: 'शेतकरी पोर्टल',
    consumerPortal: 'ग्राहक पोर्टल',
    adminPortal: 'अ‍ॅडमिन पोर्टल',
  },
  gu: {
    welcome: 'સ્વાગત',
    goodMorning: 'શુભ સવાર',
    hello: 'નમસ્તે',
    logout: 'લૉગ આઉટ',
    back: 'પાછા',
    cancel: 'રદ',
    save: 'સાચવો',
    delete: 'કાઢો',
    edit: 'સંપાદિત',
    add: 'ઉમેરો',
    search: 'શોધો',
    loading: 'લોડ થઈ રહ્યું છે...',
    noResults: 'કોઈ પરિણામ નથી',
    createAccount: 'ખાતું બનાવો',
    signIn: 'સાઇન ઇન',
    signUp: 'સાઇન અપ',
    email: 'ઈમેઈલ',
    password: 'પાસવર્ડ',
    fullName: 'પૂરું નામ',
    phone: 'ફોન',
    farmName: 'ખેતરનું નામ / સ્થાન',
    selectLanguage: 'પસંદગીની ભાષા',
    alreadyHaveAccount: 'પહેલેથી ખાતું છે?',
    fillDetails: 'શરૂ કરવા વિગતો ભરો',
    signingUpAs: 'તરીકે સાઇન અપ',
    creatingAccount: 'બનાવી રહ્યા છીએ...',
    dashboard: 'ડૅશબોર્ડ',
    products: 'ઉત્પાદનો',
    orders: 'ઓર્ડર',
    climate: 'હવામાન',
    pricing: 'ભાવ',
    chat: 'ચેટ',
    qualityScan: 'ગુણવત્તા સ્કેન',
    home: 'હોમ',
    browse: 'બ્રાઉઝ',
    cart: 'કાર્ટ',
    overview: 'ઝાંખી',
    users: 'વપરાશકર્તાઓ',
    revenue: 'આવક',
    disputes: 'વિવાદ',
    settings: 'સેટિંગ્સ',
    myProducts: 'મારા ઉત્પાદનો',
    addProduct: 'ઉત્પાદન ઉમેરો',
    productsListed: 'ઉત્પાદનો સૂચિબદ્ધ',
    noProductsYet: 'હજુ કોઈ ઉત્પાદન નથી',
    addFirstProduct: 'ગ્રાહકોને વેચવા માટે પ્રથમ ઉત્પાદન ઉમેરો.',
    productName: 'ઉત્પાદનનું નામ',
    price: 'ભાવ',
    category: 'શ્રેણી',
    unit: 'એકમ',
    grade: 'ગ્રેડ',
    description: 'વર્ણન',
    organicProduct: 'ઓર્ગેનિક ઉત્પાદન',
    inStock: 'સ્ટૉકમાં',
    outOfStock: 'સ્ટૉકમાં નથી',
    todaysEarnings: 'આજની કમાણી',
    activeOrders: 'સક્રિય ઓર્ડર',
    aiPriceScore: 'AI ભાવ સ્કોર',
    weeklyEarnings: 'સાપ્તાહિક કમાણી',
    recentOrders: 'તાજેતરના ઓર્ડર',
    viewAll: 'બધા જુઓ',
    aiInsights: '🤖 AI આંતરદૃષ્ટિ',
    farmOverview: 'આજનું તમારા ખેતરનું ઝાંખી',
    freshProduce: 'તાજી ઉપજ',
    freshFromFarm: 'ખેતરમાંથી સીધી તમારા ટેબલ પર',
    searchProducts: 'ઉત્પાદનો, ખેતર શોધો...',
    nearbyFarms: 'નજીકના ખેતરો',
    addToCart: 'કાર્ટમાં ઉમેરો',
    discoverFarms: 'ખેતરો શોધો',
    all: 'બધા',
    vegetables: 'શાકભાજી',
    fruits: 'ફળો',
    grains: 'અનાજ',
    dairy: 'ડેરી',
    organic: 'ઓર્ગેનિક',
    farmerPortal: 'ખેડૂત પોર્ટલ',
    consumerPortal: 'ગ્રાહક પોર્ટલ',
    adminPortal: 'એડમિન પોર્ટલ',
  },
  pa: {
    welcome: 'ਜੀ ਆਇਆਂ ਨੂੰ',
    goodMorning: 'ਸ਼ੁਭ ਸਵੇਰ',
    hello: 'ਸਤ ਸ੍ਰੀ ਅਕਾਲ',
    logout: 'ਲੌਗ ਆਊਟ',
    back: 'ਪਿੱਛੇ',
    cancel: 'ਰੱਦ',
    save: 'ਸੁਰੱਖਿਅਤ',
    delete: 'ਮਿਟਾਓ',
    edit: 'ਸੋਧੋ',
    add: 'ਜੋੜੋ',
    search: 'ਖੋਜੋ',
    loading: 'ਲੋਡ ਹੋ ਰਿਹਾ ਹੈ...',
    noResults: 'ਕੋਈ ਨਤੀਜੇ ਨਹੀਂ',
    createAccount: 'ਖਾਤਾ ਬਣਾਓ',
    signIn: 'ਸਾਈਨ ਇਨ',
    signUp: 'ਸਾਈਨ ਅੱਪ',
    email: 'ਈਮੇਲ',
    password: 'ਪਾਸਵਰਡ',
    fullName: 'ਪੂਰਾ ਨਾਮ',
    phone: 'ਫ਼ੋਨ',
    farmName: 'ਖੇਤ ਦਾ ਨਾਮ / ਥਾਂ',
    selectLanguage: 'ਪਸੰਦੀਦਾ ਭਾਸ਼ਾ',
    alreadyHaveAccount: 'ਪਹਿਲਾਂ ਤੋਂ ਖਾਤਾ ਹੈ?',
    fillDetails: 'ਸ਼ੁਰੂ ਕਰਨ ਲਈ ਵੇਰਵੇ ਭਰੋ',
    signingUpAs: 'ਵਜੋਂ ਸਾਈਨ ਅੱਪ',
    creatingAccount: 'ਬਣਾ ਰਿਹਾ ਹੈ...',
    dashboard: 'ਡੈਸ਼ਬੋਰਡ',
    products: 'ਉਤਪਾਦ',
    orders: 'ਆਰਡਰ',
    climate: 'ਮੌਸਮ',
    pricing: 'ਕੀਮਤ',
    chat: 'ਚੈਟ',
    qualityScan: 'ਗੁਣਵੱਤਾ ਸਕੈਨ',
    home: 'ਹੋਮ',
    browse: 'ਬ੍ਰਾਊਜ਼',
    cart: 'ਕਾਰਟ',
    overview: 'ਸੰਖੇਪ',
    users: 'ਵਰਤੋਂਕਾਰ',
    revenue: 'ਮਾਲੀਆ',
    disputes: 'ਵਿਵਾਦ',
    settings: 'ਸੈਟਿੰਗਜ਼',
    myProducts: 'ਮੇਰੇ ਉਤਪਾਦ',
    addProduct: 'ਉਤਪਾਦ ਜੋੜੋ',
    productsListed: 'ਉਤਪਾਦ ਸੂਚੀਬੱਧ',
    noProductsYet: 'ਅਜੇ ਕੋਈ ਉਤਪਾਦ ਨਹੀਂ',
    addFirstProduct: 'ਖਪਤਕਾਰਾਂ ਨੂੰ ਵੇਚਣ ਲਈ ਪਹਿਲਾ ਉਤਪਾਦ ਜੋੜੋ।',
    productName: 'ਉਤਪਾਦ ਦਾ ਨਾਮ',
    price: 'ਕੀਮਤ',
    category: 'ਸ਼੍ਰੇਣੀ',
    unit: 'ਇਕਾਈ',
    grade: 'ਗ੍ਰੇਡ',
    description: 'ਵੇਰਵਾ',
    organicProduct: 'ਜੈਵਿਕ ਉਤਪਾਦ',
    inStock: 'ਸਟਾਕ ਵਿੱਚ',
    outOfStock: 'ਸਟਾਕ ਵਿੱਚ ਨਹੀਂ',
    todaysEarnings: 'ਅੱਜ ਦੀ ਕਮਾਈ',
    activeOrders: 'ਸਰਗਰਮ ਆਰਡਰ',
    aiPriceScore: 'AI ਕੀਮਤ ਸਕੋਰ',
    weeklyEarnings: 'ਹਫ਼ਤਾਵਾਰੀ ਕਮਾਈ',
    recentOrders: 'ਤਾਜ਼ਾ ਆਰਡਰ',
    viewAll: 'ਸਭ ਦੇਖੋ',
    aiInsights: '🤖 AI ਸੂਝ',
    farmOverview: 'ਅੱਜ ਦਾ ਤੁਹਾਡੇ ਖੇਤ ਦਾ ਸੰਖੇਪ',
    freshProduce: 'ਤਾਜ਼ੀ ਉਪਜ',
    freshFromFarm: 'ਖੇਤ ਤੋਂ ਸਿੱਧੀ ਤੁਹਾਡੀ ਮੇਜ਼ ਤੇ',
    searchProducts: 'ਉਤਪਾਦ, ਖੇਤ ਖੋਜੋ...',
    nearbyFarms: 'ਨੇੜੇ ਦੇ ਖੇਤ',
    addToCart: 'ਕਾਰਟ ਵਿੱਚ ਜੋੜੋ',
    discoverFarms: 'ਖੇਤ ਲੱਭੋ',
    all: 'ਸਭ',
    vegetables: 'ਸਬਜ਼ੀਆਂ',
    fruits: 'ਫਲ',
    grains: 'ਅਨਾਜ',
    dairy: 'ਡੇਅਰੀ',
    organic: 'ਜੈਵਿਕ',
    farmerPortal: 'ਕਿਸਾਨ ਪੋਰਟਲ',
    consumerPortal: 'ਖਪਤਕਾਰ ਪੋਰਟਲ',
    adminPortal: 'ਐਡਮਿਨ ਪੋਰਟਲ',
  },
  ml: {
    welcome: 'സ്വാഗതം',
    goodMorning: 'സുപ്രഭാതം',
    hello: 'ഹലോ',
    logout: 'ലോഗ് ഔട്ട്',
    back: 'പിന്നോട്ട്',
    cancel: 'റദ്ദാക്കുക',
    save: 'സംരക്ഷിക്കുക',
    delete: 'ഇല്ലാതാക്കുക',
    edit: 'എഡിറ്റ്',
    add: 'ചേർക്കുക',
    search: 'തിരയുക',
    loading: 'ലോഡ് ചെയ്യുന്നു...',
    noResults: 'ഫലങ്ങളൊന്നും ഇല്ല',
    createAccount: 'അക്കൗണ്ട് സൃഷ്ടിക്കുക',
    signIn: 'സൈൻ ഇൻ',
    signUp: 'സൈൻ അപ്',
    email: 'ഇമെയിൽ',
    password: 'പാസ്‌വേഡ്',
    fullName: 'പൂർണ നാമം',
    phone: 'ഫോൺ',
    farmName: 'കൃഷിസ്ഥലത്തിന്റെ പേര് / സ്ഥാനം',
    selectLanguage: 'ഇഷ്ടപ്പെട്ട ഭാഷ',
    alreadyHaveAccount: 'ഇതിനകം അക്കൗണ്ട് ഉണ്ടോ?',
    fillDetails: 'ആരംഭിക്കാൻ വിശദാംശങ്ങൾ നൽകുക',
    signingUpAs: 'ആയി സൈൻ അപ്',
    creatingAccount: 'സൃഷ്ടിക്കുന്നു...',
    dashboard: 'ഡാഷ്‌ബോർഡ്',
    products: 'ഉൽപ്പന്നങ്ങൾ',
    orders: 'ഓർഡറുകൾ',
    climate: 'കാലാവസ്ഥ',
    pricing: 'വിലനിർണ്ണയം',
    chat: 'ചാറ്റ്',
    qualityScan: 'ഗുണനിലവാര സ്‌കാൻ',
    home: 'ഹോം',
    browse: 'ബ്രൗസ്',
    cart: 'കാർട്ട്',
    overview: 'അവലോകനം',
    users: 'ഉപയോക്താക്കൾ',
    revenue: 'വരുമാനം',
    disputes: 'തർക്കങ്ങൾ',
    settings: 'ക്രമീകരണങ്ങൾ',
    myProducts: 'എന്റെ ഉൽപ്പന്നങ്ങൾ',
    addProduct: 'ഉൽപ്പന്നം ചേർക്കുക',
    productsListed: 'ഉൽപ്പന്നങ്ങൾ ലിസ്റ്റ് ചെയ്തു',
    noProductsYet: 'ഇതുവരെ ഉൽപ്പന്നങ്ങൾ ഇല്ല',
    addFirstProduct: 'ഉപഭോക്താക്കൾക്ക് വിൽക്കാൻ ആദ്യ ഉൽപ്പന്നം ചേർക്കുക.',
    productName: 'ഉൽപ്പന്ന നാമം',
    price: 'വില',
    category: 'വിഭാഗം',
    unit: 'യൂണിറ്റ്',
    grade: 'ഗ്രേഡ്',
    description: 'വിവരണം',
    organicProduct: 'ജൈവ ഉൽപ്പന്നം',
    inStock: 'സ്റ്റോക്കിൽ ഉണ്ട്',
    outOfStock: 'സ്റ്റോക്കിൽ ഇല്ല',
    todaysEarnings: 'ഇന്നത്തെ വരുമാനം',
    activeOrders: 'സജീവ ഓർഡറുകൾ',
    aiPriceScore: 'AI വില സ്‌കോർ',
    weeklyEarnings: 'പ്രതിവാര വരുമാനം',
    recentOrders: 'സമീപകാല ഓർഡറുകൾ',
    viewAll: 'എല്ലാം കാണുക',
    aiInsights: '🤖 AI ഉൾക്കാഴ്ചകൾ',
    farmOverview: 'ഇന്നത്തെ നിങ്ങളുടെ കൃഷി അവലോകനം',
    freshProduce: 'പുതിയ ഉൽപ്പന്നം',
    freshFromFarm: 'കൃഷിയിടത്തിൽ നിന്ന് നേരിട്ട്',
    searchProducts: 'ഉൽപ്പന്നങ്ങൾ, കൃഷിയിടങ്ങൾ തിരയുക...',
    nearbyFarms: 'സമീപത്തെ കൃഷിയിടങ്ങൾ',
    addToCart: 'കാർട്ടിൽ ചേർക്കുക',
    discoverFarms: 'കൃഷിയിടങ്ങൾ കണ്ടെത്തുക',
    all: 'എല്ലാം',
    vegetables: 'പച്ചക്കറികൾ',
    fruits: 'പഴങ്ങൾ',
    grains: 'ധാന്യങ്ങൾ',
    dairy: 'ക്ഷീര ഉൽപ്പന്നങ്ങൾ',
    organic: 'ജൈവ',
    farmerPortal: 'കർഷക പോർട്ടൽ',
    consumerPortal: 'ഉപഭോക്തൃ പോർട്ടൽ',
    adminPortal: 'അഡ്മിൻ പോർട്ടൽ',
  },
};

interface LanguageContextType {
  language: LanguageCode;
  setLanguage: (lang: LanguageCode) => void;
  t: TranslationKeys;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguageState] = useState<LanguageCode>('en');
  const { user } = useApp();

  useEffect(() => {
    if (user) {
      // Load language from profile
      supabase
        .from('profiles')
        .select('language')
        .eq('user_id', user.id)
        .single()
        .then(({ data }) => {
          if (data?.language && data.language in translations) {
            setLanguageState(data.language as LanguageCode);
          }
        });
    }
  }, [user]);

  const setLanguage = async (lang: LanguageCode) => {
    setLanguageState(lang);
    if (user) {
      await supabase
        .from('profiles')
        .update({ language: lang })
        .eq('user_id', user.id);
    }
  };

  const t = translations[language] || translations.en;

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be used within LanguageProvider');
  return ctx;
};
